// <auto-generated />
using System;
using Assgment_Nhom3_WebBanDienThoai.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assgment_Nhom3_WebBanDienThoai.Migrations
{
    [DbContext(typeof(ShoppingDbContext))]
    [Migration("20230612154502_vipPro")]
    partial class vipPro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.BoNhoTrong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoNhoTrongs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatLieus");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CameraSau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraTruoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoPhanGiaiManHinh")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdBoNhoTrong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChipCPU")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChipGPU")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCongSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHeDieuHanh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPin")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSim")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<double>("TrongLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdBoNhoTrong");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdChipCPU");

                    b.HasIndex("IdChipGPU");

                    b.HasIndex("IdCongSac");

                    b.HasIndex("IdGiamGia");

                    b.HasIndex("IdHeDieuHanh");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdPin");

                    b.HasIndex("IdRam");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdSim");

                    b.ToTable("ChiTietSanPhams");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ChipCPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChipCPUs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ChipGPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChipGPUs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.CongSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CongSacs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.DanhGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSpct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdSpct");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.GiamGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoPhanTramGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.GioHang", b =>
                {
                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaiKhoan");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChiTietSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietSp");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.HeDieuHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeDieuHanhs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.HinhThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHd")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHd");

                    b.HasIndex("IdThanhToan");

                    b.ToTable("HinhThucThanhToans");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SDT")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdChiTietSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietSp");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.Imei", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCtsp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("imei")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCtsp");

                    b.ToTable("Imeis");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ListAnh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Anh1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Anh2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Anh3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdCtsp")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdCtsp");

                    b.ToTable("ListAnhs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.NhaSanXuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhaSanXuats");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.PhanQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.Pin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.Ram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdHsx")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdHsx");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.Sim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sims");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdCv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCv");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaCvv")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.TinTuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.BoNhoTrong", "BoNhoTrongs")
                        .WithMany()
                        .HasForeignKey("IdBoNhoTrong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChatLieu", "ChatLieus")
                        .WithMany()
                        .HasForeignKey("IdChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChipCPU", "ChipCPUs")
                        .WithMany()
                        .HasForeignKey("IdChipCPU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChipGPU", "ChipGPUs")
                        .WithMany()
                        .HasForeignKey("IdChipGPU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.CongSac", "CongSacs")
                        .WithMany()
                        .HasForeignKey("IdCongSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.GiamGia", "GiamGias")
                        .WithMany()
                        .HasForeignKey("IdGiamGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.HeDieuHanh", "HeDieuHanhs")
                        .WithMany()
                        .HasForeignKey("IdHeDieuHanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.MauSac", "MauSacs")
                        .WithMany()
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.Pin", "Pins")
                        .WithMany()
                        .HasForeignKey("IdPin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.Ram", "Rams")
                        .WithMany()
                        .HasForeignKey("IdRam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.SanPham", "SanPhams")
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.Sim", "Sims")
                        .WithMany()
                        .HasForeignKey("IdSim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoNhoTrongs");

                    b.Navigation("ChatLieus");

                    b.Navigation("ChipCPUs");

                    b.Navigation("ChipGPUs");

                    b.Navigation("CongSacs");

                    b.Navigation("GiamGias");

                    b.Navigation("HeDieuHanhs");

                    b.Navigation("MauSacs");

                    b.Navigation("Pins");

                    b.Navigation("Rams");

                    b.Navigation("SanPhams");

                    b.Navigation("Sims");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.DanhGia", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChiTietSanPham", "ChiTietSanPhams")
                        .WithMany()
                        .HasForeignKey("IdSpct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.TaiKhoan", "TaiKhoans")
                        .WithMany()
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPhams");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.GioHang", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.TaiKhoan", "TaiKhoans")
                        .WithOne("GioHangs")
                        .HasForeignKey("Assgment_Nhom3_WebBanDienThoai.Models.GioHang", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChiTietSanPham", "ChiTietSanPhams")
                        .WithMany()
                        .HasForeignKey("IdChiTietSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.GioHang", "GioHangs")
                        .WithMany()
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPhams");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.HinhThucThanhToan", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.HoaDon", "HoaDons")
                        .WithMany()
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ThanhToan", "ThanhToans")
                        .WithMany()
                        .HasForeignKey("IdThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.HoaDon", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.TaiKhoan", "TaiKhoans")
                        .WithMany()
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChiTietSanPham", "ChiTietSanPhams")
                        .WithMany()
                        .HasForeignKey("IdChiTietSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.HoaDon", "HoaDons")
                        .WithMany()
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPhams");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.Imei", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChiTietSanPham", "ChiTietSanPhams")
                        .WithMany()
                        .HasForeignKey("IdCtsp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.ListAnh", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.ChiTietSanPham", "ChiTietSanPhams")
                        .WithMany()
                        .HasForeignKey("IdCtsp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.SanPham", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.NhaSanXuat", "NhaSanXuats")
                        .WithMany()
                        .HasForeignKey("IdHsx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaSanXuats");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.TaiKhoan", b =>
                {
                    b.HasOne("Assgment_Nhom3_WebBanDienThoai.Models.PhanQuyen", "PhanQuyens")
                        .WithMany()
                        .HasForeignKey("IdCv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("Assgment_Nhom3_WebBanDienThoai.Models.TaiKhoan", b =>
                {
                    b.Navigation("GioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
